"""add ai_recommendations

Revision ID: 46e5951cae12
Revises: f4574a20bfc6
Create Date: 2026-08-20 05:53:40.198915+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46e5951cae12"
down_revision: Union[str, None] = "f4574a20bfc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_recommendations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("item_crop_id", sa.String(), nullable=True),
        sa.Column("agent_key_id", sa.String(), nullable=False),
        sa.Column("proposed_retail_unit_cents", sa.Integer(), nullable=False),
        sa.Column("proposed_shipping_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("source_retailer", sa.String(), nullable=False),
        sa.Column("match_type", sa.String(), nullable=False),
        sa.Column("product_title", sa.String(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_captured_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_key_id"],
            ["agent_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_crop_id"],
            ["item_crops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_recommendations_item_id"), "ai_recommendations", ["item_id"], unique=False
    )
    # NOTE: autogenerate also proposed dropping 'feedback' and 'feedback_comments'.
    # This is a known pre-existing quirk: models_feedback is not wired into the
    # metadata autogenerate compares against. Those tables are unrelated to this
    # migration and were intentionally omitted here — do not drop them.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_recommendations_item_id"), table_name="ai_recommendations")
    op.drop_table("ai_recommendations")
    # ### end Alembic commands ###
