"""add agent_keys

Revision ID: f4574a20bfc6
Revises: 3ef892b412e1
Create Date: 2026-08-20 05:47:59.301399+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4574a20bfc6'
down_revision: Union[str, None] = '3ef892b412e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_keys_key_prefix'), 'agent_keys', ['key_prefix'], unique=False)
    # NOTE: autogenerate also proposed dropping 'feedback' and 'feedback_comments'.
    # This is a known pre-existing quirk: models_feedback is not wired into the
    # metadata autogenerate compares against. Those tables are unrelated to this
    # migration and were intentionally omitted here — do not drop them.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_keys_key_prefix'), table_name='agent_keys')
    op.drop_table('agent_keys')
    # ### end Alembic commands ###
