"""add matter_access table

Revision ID: 7d17b10b2888
Revises: 53d00d20ce85
Create Date: 2026-04-26 13:25:22.837475+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d17b10b2888'
down_revision: Union[str, None] = '53d00d20ce85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matter_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('granted_by_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'matter_id', name='uq_user_matter')
    )
    op.create_index(op.f('ix_matter_access_matter_id'), 'matter_access', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_access_user_id'), 'matter_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matter_access_user_id'), table_name='matter_access')
    op.drop_index(op.f('ix_matter_access_matter_id'), table_name='matter_access')
    op.drop_table('matter_access')
    # ### end Alembic commands ###
