"""initial

Revision ID: 4296f3d15849
Revises: 
Create Date: 2026-04-14 21:40:59.269788+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4296f3d15849'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('useful_life_years', sa.Integer(), nullable=True),
    sa.Column('acv_floor_pct', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firm_name', sa.String(), nullable=False),
    sa.Column('attorney_name', sa.String(), nullable=False),
    sa.Column('attorney_email', sa.String(), nullable=False),
    sa.Column('policyholder_name', sa.String(), nullable=False),
    sa.Column('loss_location', sa.String(), nullable=False),
    sa.Column('loss_type', sa.String(), nullable=False),
    sa.Column('loss_event', sa.String(), nullable=False),
    sa.Column('loss_date', sa.Date(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=False),
    sa.Column('coverage_c_limit', sa.Integer(), nullable=False),
    sa.Column('firm_file_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_delivery_date', sa.Date(), nullable=True),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('invoice_amount_cents', sa.Integer(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('scanned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('age_years', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('rcv_unit_cents', sa.Integer(), nullable=False),
    sa.Column('rcv_total_cents', sa.Integer(), nullable=False),
    sa.Column('acv_total_cents', sa.Integer(), nullable=False),
    sa.Column('acv_override_cents', sa.Integer(), nullable=True),
    sa.Column('acv_override_reason', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('source_retailer', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_captured_at', sa.DateTime(), nullable=True),
    sa.Column('source_screenshot_path', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vision_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('evidence_file_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['evidence_files.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vision_runs')
    op.drop_table('items')
    op.drop_table('rooms')
    op.drop_table('evidence_files')
    op.drop_table('matters')
    op.drop_table('categories')
    # ### end Alembic commands ###
