"""rbac v2 grants

Revision ID: f8eb20311be3
Revises: 438d468b59ca
Create Date: 2026-07-16 05:53:28.450700+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8eb20311be3'
down_revision: Union[str, None] = '438d468b59ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_grants',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('group_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_role', sa.VARCHAR(), nullable=False),
    sa.Column('scope', sa.VARCHAR(), nullable=False),
    sa.Column('granted_by_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', 'user_role', 'scope', name=op.f('uq_role_grant'))
    )
    op.create_index(op.f('ix_role_grants_user_id'), 'role_grants', ['user_id'], unique=False)
    op.create_index(op.f('ix_role_grants_group_id'), 'role_grants', ['group_id'], unique=False)
    op.create_table('role_grant_claims',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('grant_id', sa.VARCHAR(), nullable=False),
    sa.Column('claim_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['role_grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_grant_claims_grant_id'), 'role_grant_claims', ['grant_id'], unique=False)
    op.create_index(op.f('ix_role_grant_claims_claim_id'), 'role_grant_claims', ['claim_id'], unique=False)
    op.create_table('role_grant_overrides',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('grant_id', sa.VARCHAR(), nullable=False),
    sa.Column('object_type', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['role_grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_grant_overrides_grant_id'), 'role_grant_overrides', ['grant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_grant_overrides_grant_id'), table_name='role_grant_overrides')
    op.drop_table('role_grant_overrides')
    op.drop_index(op.f('ix_role_grant_claims_claim_id'), table_name='role_grant_claims')
    op.drop_index(op.f('ix_role_grant_claims_grant_id'), table_name='role_grant_claims')
    op.drop_table('role_grant_claims')
    op.drop_index(op.f('ix_role_grants_group_id'), table_name='role_grants')
    op.drop_index(op.f('ix_role_grants_user_id'), table_name='role_grants')
    op.drop_table('role_grants')
    # ### end Alembic commands ###
