"""item_crops_serp_searches_search_hint

Revision ID: cf42abfe3ff8
Revises: 4296f3d15849
Create Date: 2026-04-23 15:00:01.950469+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf42abfe3ff8'
down_revision: Union[str, None] = '4296f3d15849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_crops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('evidence_file_id', sa.String(), nullable=False),
    sa.Column('bbox_left', sa.Integer(), nullable=False),
    sa.Column('bbox_upper', sa.Integer(), nullable=False),
    sa.Column('bbox_right', sa.Integer(), nullable=False),
    sa.Column('bbox_lower', sa.Integer(), nullable=False),
    sa.Column('crop_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['evidence_files.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serp_searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_crop_id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('request_url', sa.String(), nullable=False),
    sa.Column('request_params', sa.Text(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_crop_id'], ['item_crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('search_hint', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Backfill: parse search_hint from notes field
    import re as _re

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, notes FROM items WHERE notes LIKE '%search_hint:%'")).fetchall()
    for row in rows:
        match = _re.search(r'search_hint:([^|]*)', row.notes or "")
        hint = match.group(1).strip() if match else None
        if hint:
            conn.execute(
                sa.text("UPDATE items SET search_hint = :hint WHERE id = :id"),
                {"hint": hint, "id": row.id},
            )
        # Strip search_hint segment from notes
        cleaned = _re.sub(r'\|?search_hint:[^|]*', '', row.notes or "").strip("|").strip()
        conn.execute(
            sa.text("UPDATE items SET notes = :notes WHERE id = :id"),
            {"notes": cleaned, "id": row.id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'search_hint')
    op.drop_table('serp_searches')
    op.drop_table('item_crops')
    # ### end Alembic commands ###
