"""add matter ownership and item confirmed_by columns

Revision ID: 53d00d20ce85
Revises: 87fac388db1b
Create Date: 2026-04-26 13:23:50.143694+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d00d20ce85'
down_revision: Union[str, None] = '87fac388db1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # SQLite batch mode for items table
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_by_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    # Add FK for items separately (after table restructure)
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_items_confirmed_by_id', 'users', ['confirmed_by_id'], ['id'])

    # SQLite batch mode for matters table
    with op.batch_alter_table('matters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_group_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.String(), nullable=True))

    # Add FKs for matters separately (after table restructure)
    with op.batch_alter_table('matters', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_matters_created_by_id', 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('fk_matters_owner_group_id', 'groups', ['owner_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # SQLite batch mode for matters table
    with op.batch_alter_table('matters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_matters_owner_group_id', type_='foreignkey')
        batch_op.drop_constraint('fk_matters_created_by_id', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('owner_group_id')

    # SQLite batch mode for items table
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_confirmed_by_id', type_='foreignkey')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('confirmed_by_id')
    # ### end Alembic commands ###
