"""item_crops_adjusted_bbox

Revision ID: 6b547029fe90
Revises: cf42abfe3ff8
Create Date: 2026-04-24 04:34:50.007669+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b547029fe90'
down_revision: Union[str, None] = 'cf42abfe3ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_crops', sa.Column('adjusted_bbox_left', sa.Integer(), nullable=True))
    op.add_column('item_crops', sa.Column('adjusted_bbox_upper', sa.Integer(), nullable=True))
    op.add_column('item_crops', sa.Column('adjusted_bbox_right', sa.Integer(), nullable=True))
    op.add_column('item_crops', sa.Column('adjusted_bbox_lower', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_crops', 'adjusted_bbox_lower')
    op.drop_column('item_crops', 'adjusted_bbox_right')
    op.drop_column('item_crops', 'adjusted_bbox_upper')
    op.drop_column('item_crops', 'adjusted_bbox_left')
    # ### end Alembic commands ###
