"""add crop_updated_at to item_crops

Revision ID: d41ffbf06ede
Revises: 8b3f4be73872
Create Date: 2026-05-11 09:05:17.875752+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41ffbf06ede'
down_revision: Union[str, None] = '8b3f4be73872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_crops', sa.Column('crop_updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_vision_models_one_default'), table_name='vision_models', sqlite_where=sa.text('is_default = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vision_models_one_default'), 'vision_models', ['is_default'], unique=1, sqlite_where=sa.text('is_default = 1'))
    op.drop_column('item_crops', 'crop_updated_at')
    # ### end Alembic commands ###
